### ISSUE TITLE
Keybinding for "Open Preview" conflicts with Workbench Quick Open

### ISSUE THREAD

**Issue by ADTC** [kirchner-trevor/vscode-shopify-liquid-preview#2]
`Ctrl+P` is the standard keyboard shortcut for **Quick Open** (`workbench.action.quickOpen`) in _Visual Studio Code_ and it is promoted as such in the Welcome screen.

After installing the _Shopify Liquid Preview_ extension, `Ctrl+P` stops working as intended because of the extension's key binding contribution `Ctrl+P L`. Now, pressing `Ctrl+P` doesn't open Quick Open but instead shows the following message in the status bar:

    (Ctrl+P) was pressed. Waiting for second key of chord...

Please choose a different non-conflicting keyboard shortcut for **Shopify Liquid: Open Preview** (`shopifyLiquidPreview.preview`).

**Note to anyone else here because of same issue:** As a workaround, you can press `Ctrl+E` to launch Quick Open. You can also edit the keybindings in _Keyboard Shortcuts_ settings.

**Comment by kirchner-trevor** [comment]
Thank you for the feedback! This is fixed in version 1.0.2 and is now available on the marketplace.
