### ISSUE TITLE
Ctrl+Shift+P isn't working

### ISSUE THREAD

**Issue by MisinformedDNA** [kirchner-trevor/vscode-shopify-liquid-preview#5]
Ctrl+Shift+P is bound to "View -> Command Palette"

Furthermore, if I look at the installed commands, Ctrl+Shift+P is not listed.

![image](https://user-images.githubusercontent.com/1784452/37665321-f610386c-2c2a-11e8-9164-bbf14f9151a7.png)

VS Code: v1.21.1
Liquid Preview: v1.0.2

**Comment by nguyenmv2** [comment]
@MisinformedDNA  Ctrl+Shift+P is the stock vscode's keybinding for the command palette. Inside the command palette, you can type in Shopify to find the Preview template option from the plugin.
