### ISSUE TITLE
Live preview warning

### ISSUE THREAD

**Issue by OnnoH** [kirchner-trevor/vscode-shopify-liquid-preview#7]
**Followed the following recommendation:**
Extension 'kirchner-trevor.shopify-liquid-preview' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.

**Installed Plugin:**
Name: Shopify Liquid Preview
Id: kirchner-trevor.shopify-liquid-preview
Description: Live preview for Shopify Liquid templates
Version: 1.0.2
Publisher: Trevor Kirchner
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=kirchner-trevor.shopify-liquid-preview

**Comment by jccit** [comment]
This extension no longer works as the `vscode.previewHtml` command has been fully removed from VS Code. Trying to open a preview returns an error `command 'vscode.previewHtml' not found`

**Comment by kirchner-trevor** [comment]
This issue has been fixed as of the 2.0.0 release.
